#!/usr/bin/env perl

use strict;
use warnings;

use Mojo::File 'curfile';
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application. Run with morbo ./script/first_app
Mojolicious::Commands->start_app('FirstApp');
